/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aptech.qldsv.form;

import com.aptech.qldsv.controller.ClassController;
import com.aptech.qldsv.controller.StudentController;
import com.aptech.qldsv.controller.SubjectController;
import com.aptech.qldsv.dao.SubjectDAO;
import com.aptech.qldsv.entity.Classes;
import com.aptech.qldsv.entity.Student;
import com.aptech.qldsv.entity.Subject;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author skulbk
 */
public final class MainForm extends javax.swing.JFrame {

    ClassController classController = new ClassController();
    SubjectController subjectController = new SubjectController();
    StudentController studentController = new StudentController();
//    DiemDAO diemDAO = new DiemDAO();
    List classId = new ArrayList();
    Map mapClass = new HashMap<>();
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        String tenDangNhap = System.getProperty("Admin");
        if (tenDangNhap == null) {
            LoginForm login = new LoginForm(this);
            login.setVisible(true);
        }
        genderBtnGroup.add(radioMale);
        genderBtnGroup.add(radioFemale);
        reload();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGroup = new javax.swing.ButtonGroup();
        pnlSidebar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblwelcome = new javax.swing.JLabel();
        pnlLop = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        btnAddClass = new javax.swing.JButton();
        btnUpdateClass = new javax.swing.JButton();
        btnDeleteClass = new javax.swing.JButton();
        btnClearClass = new javax.swing.JButton();
        txtClassId = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblClass = new javax.swing.JTable();
        pnlMon = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSubjectName = new javax.swing.JTextField();
        btnAddSubject = new javax.swing.JButton();
        btnUpdateSubject = new javax.swing.JButton();
        btnDeleteSubject = new javax.swing.JButton();
        btnClearSubject = new javax.swing.JButton();
        txtSubjectId = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSubject = new javax.swing.JTable();
        pnlSV = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtBirthday = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        btnAddStudent = new javax.swing.JButton();
        btnUpdateStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnClearStudent = new javax.swing.JButton();
        txtStudentId = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        test1 = new javax.swing.JButton();
        cbClass = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        pnlDiem = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnThemdiem = new javax.swing.JButton();
        btnSuadiem = new javax.swing.JButton();
        btnXoadiem = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        pnlDSSV1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDSDiem = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnDangXuat = new javax.swing.JMenuItem();
        mnThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm");

        pnlSidebar.setMaximumSize(new java.awt.Dimension(30, 100));
        pnlSidebar.setMinimumSize(new java.awt.Dimension(30, 100));
        pnlSidebar.setLayout(new javax.swing.BoxLayout(pnlSidebar, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton1);

        jButton2.setText("Lớp");
        jButton2.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(85, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton2);

        jButton3.setText("Môn");
        jButton3.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton3);

        jButton4.setText("Sinh viên");
        jButton4.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton4);

        jButton5.setText("Điểm");
        jButton5.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton5);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.LINE_START);

        pnlContent.setLayout(new java.awt.CardLayout());

        lblwelcome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblwelcome.setText("Welcome");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(lblwelcome)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblwelcome)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        pnlContent.add(pnlDashboard, "cardDashboard");

        pnlLop.setPreferredSize(new java.awt.Dimension(85, 23));

        jLabel11.setText("Id");

        jLabel12.setText("Tên lớp");

        btnAddClass.setText("Thêm");
        btnAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClassActionPerformed(evt);
            }
        });

        btnUpdateClass.setText("Sửa");
        btnUpdateClass.setEnabled(false);
        btnUpdateClass.setPreferredSize(new java.awt.Dimension(73, 23));
        btnUpdateClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateClassActionPerformed(evt);
            }
        });

        btnDeleteClass.setText("Xóa");
        btnDeleteClass.setEnabled(false);
        btnDeleteClass.setPreferredSize(new java.awt.Dimension(73, 23));
        btnDeleteClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClassActionPerformed(evt);
            }
        });

        btnClearClass.setText("Nhập lại");
        btnClearClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearClassActionPerformed(evt);
            }
        });

        txtClassId.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClassName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtClassId, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClearClass))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAddClass, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateClass, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtClassId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(276, 276, 276)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddClass)
                    .addComponent(btnUpdateClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearClass)
                .addGap(103, 103, 103))
        );

        tblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClassMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblClass);

        javax.swing.GroupLayout pnlLopLayout = new javax.swing.GroupLayout(pnlLop);
        pnlLop.setLayout(pnlLopLayout);
        pnlLopLayout.setHorizontalGroup(
            pnlLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLopLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
        );
        pnlLopLayout.setVerticalGroup(
            pnlLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLopLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlContent.add(pnlLop, "cardLop");

        pnlMon.setPreferredSize(new java.awt.Dimension(85, 23));

        jLabel4.setText("Id");

        jLabel10.setText("Tên môn");

        btnAddSubject.setText("Thêm");
        btnAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSubjectActionPerformed(evt);
            }
        });

        btnUpdateSubject.setText("Sửa");
        btnUpdateSubject.setEnabled(false);
        btnUpdateSubject.setPreferredSize(new java.awt.Dimension(73, 23));
        btnUpdateSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSubjectActionPerformed(evt);
            }
        });

        btnDeleteSubject.setText("Xóa");
        btnDeleteSubject.setEnabled(false);
        btnDeleteSubject.setPreferredSize(new java.awt.Dimension(73, 23));
        btnDeleteSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSubjectActionPerformed(evt);
            }
        });

        btnClearSubject.setText("Nhập lại");
        btnClearSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSubjectActionPerformed(evt);
            }
        });

        txtSubjectId.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubjectName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSubjectId, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAddSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClearSubject))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btnUpdateSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSubjectId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(275, 275, 275)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSubject)
                    .addComponent(btnUpdateSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearSubject)
                .addGap(104, 104, 104))
        );

        tblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSubjectMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblSubject);

        javax.swing.GroupLayout pnlMonLayout = new javax.swing.GroupLayout(pnlMon);
        pnlMon.setLayout(pnlMonLayout);
        pnlMonLayout.setHorizontalGroup(
            pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
        );
        pnlMonLayout.setVerticalGroup(
            pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMonLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlContent.add(pnlMon, "cardMon");

        pnlSV.setMinimumSize(new java.awt.Dimension(850, 500));
        pnlSV.setName(""); // NOI18N
        pnlSV.setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel1.setText("Id");

        jLabel6.setText("Họ tên");

        jLabel7.setText("Ngày sinh");

        jLabel8.setText("Giới tính");

        jLabel9.setText("Địa chỉ");

        radioMale.setText("Name");

        radioFemale.setText("Nữ");

        btnAddStudent.setText("Thêm");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnUpdateStudent.setText("Sửa");
        btnUpdateStudent.setEnabled(false);
        btnUpdateStudent.setPreferredSize(new java.awt.Dimension(73, 23));
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });

        btnDeleteStudent.setText("Xóa");
        btnDeleteStudent.setEnabled(false);
        btnDeleteStudent.setPreferredSize(new java.awt.Dimension(73, 23));
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        btnClearStudent.setText("Nhập lại");
        btnClearStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearStudentActionPerformed(evt);
            }
        });

        txtStudentId.setEnabled(false);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane3.setViewportView(txtAddress);

        test1.setText("test");
        test1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Lớp");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStudentName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtStudentId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBirthday)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(radioMale)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioFemale)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(test1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearStudent))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(radioMale)
                    .addComponent(radioFemale))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent)
                    .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearStudent)
                    .addComponent(test1))
                .addGap(102, 102, 102))
        );

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblStudent);

        javax.swing.GroupLayout pnlSVLayout = new javax.swing.GroupLayout(pnlSV);
        pnlSV.setLayout(pnlSVLayout);
        pnlSVLayout.setHorizontalGroup(
            pnlSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSVLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
        );
        pnlSVLayout.setVerticalGroup(
            pnlSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSVLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlContent.add(pnlSV, "cardSV");

        pnlDiem.setPreferredSize(new java.awt.Dimension(85, 23));
        pnlDiem.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Danh sách điểm");

        btnThemdiem.setText("Thêm");
        btnThemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemdiemActionPerformed(evt);
            }
        });

        btnSuadiem.setText("Sửa");
        btnSuadiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuadiemActionPerformed(evt);
            }
        });

        btnXoadiem.setText("Xóa");
        btnXoadiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoadiemActionPerformed(evt);
            }
        });

        btnChiTiet.setText("Chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(239, 239, 239))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemdiem)
                    .addComponent(btnSuadiem)
                    .addComponent(btnXoadiem)
                    .addComponent(btnChiTiet))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlDiem.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pnlDSSV1.setLayout(new javax.swing.BoxLayout(pnlDSSV1, javax.swing.BoxLayout.LINE_AXIS));

        tblDSDiem.setAutoCreateRowSorter(true);
        tblDSDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSDiemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDSDiem);

        pnlDSSV1.add(jScrollPane4);

        pnlDiem.add(pnlDSSV1, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlDiem, "cardDiem");

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        mnDangXuat.setText("Đăng xuất");
        mnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnDangXuat);

        mnThoat.setText("Thoát");
        mnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThoatActionPerformed(evt);
            }
        });
        jMenu1.add(mnThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadcbClass(){
        List<Classes> listClass = classController.getAllClass();
        for (int i = 0; i < listClass.size(); i++) {
            Classes c = listClass.get(i);
            classId.add(i, c.getId());
            cbClass.addItem(c.getName());
            mapClass.put(c.getId(), c.getName());
        }
    }
    
    public void welcome(String ten){
        lblwelcome.setText("Welcome "+ ten);
    }
    
    public void reload(){
        loadClassList();
        loadSubjectList();
        loadDSDiem();
        loadStudentList();
        loadcbClass();
        DisEn(false);
    }
    public void loadClassList(){
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[2];
        Object cols[] = new Object[2];
        cols[0] = "Mã lớp";
        cols[1] = "Tên Lớp";
        
        tbl.setColumnIdentifiers(cols);
        
       List<Classes> listlop = classController.getAllClass();
        
        for (int i = 0; i < listlop.size(); i++) {
            Classes c = listlop.get(i);
            rows[0] = c.getId();
            rows[1] = c.getName();
            
            tbl.addRow(rows);
        }
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblClass.getModel());
        tblClass.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        tblClass.setModel(tbl);
    }
    
    public void loadSubjectList(){
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[2];
        Object cols[] = new Object[2];
        cols[0] = "Mã môn học";
        cols[1] = "Tên môn học";
        
        tbl.setColumnIdentifiers(cols);
        
        List<Subject> listSubject = subjectController.getAllSubject();
        
        for (int i = 0; i < listSubject.size(); i++) {
            Subject m = listSubject.get(i);
            rows[0] = m.getId();
            rows[1] = m.getName();
            
            tbl.addRow(rows);
        }
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblSubject.getModel());
        tblSubject.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        tblSubject.setModel(tbl);
        tbl.fireTableDataChanged();
    }
    
    public void loadStudentList(){
        JTable table = new JTable();
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[6];
        Object cols[] = new Object[6];
        cols[0] = "Mã sinh viên";
        cols[1] = "Tên sinh viên";
        cols[2] = "Ngày sinh";
        cols[3] = "Giới tính";
        cols[4] = "Địa chỉ";
        cols[5] = "Lớp";
        
        tbl.setColumnIdentifiers(cols);
        
        List<Student> lstStudent = studentController.getAllStudent();
        List<Classes> lstClass = classController.getAllClass();
        for (int i = 0; i < lstStudent.size(); i++) {
            Student student = lstStudent.get(i);
            rows[0] = student.getId();
            rows[1] = student.getName();
            rows[2] = student.getBirthday();
            if(student.getGender()==false)
                rows[3] = "Nam";
            else
                rows[3] = "Nữ";
            rows[4] = student.getAddress();
            for (int j = 0; j < lstClass.size(); j++) {
                Classes c = lstClass.get(j);
                if(student.getClazz().getId()==c.getId())
                rows[5] = c.getName();
            }
            
            
            tbl.addRow(rows);
        }
        table.setModel(tbl);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblStudent.getModel());
        tblStudent.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        tblStudent.setModel(tbl);
    }
    
    public void loadDSDiem(){
        JTable table = new JTable();
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[6];
        Object cols[] = new Object[6];
        cols[0] = "Mã sinh viên";
        cols[1] = "Tên sinh viên";
        cols[2] = "Lớp";
        cols[3] = "Môn";
        cols[4] = "Loại điểm";
        cols[5] = "Điểm";
               
        tbl.setColumnIdentifiers(cols);
//        List<Diem> listDiem = diemDAO.getAll();
//        List<SinhVien> listSV = svDAO.getAll();
//        List<Lop> listLop = lopDAO.getAll();
//        List<LoaiDiem> listLD = ldDAO.getAll();
//        List<MonHoc> listMon = monDAO.getAll();
//        List<DSDiem> listDSD = diemDAO.getAll1();
//        for (int i = 0; i < listDiem.size(); i++) {
//            DSDiem dsd = listDSD.get(i);
//            
//            
//            rows[0] = dsd.getMaSV();
//            rows[1] = dsd.getTenSV();
//            rows[2] = dsd.getTenLop();
//            rows[3] = dsd.getTenMH();
//            rows[4] = dsd.getTenLoai();
//            rows[5] = dsd.getDiem();
//            
//            tbl.addRow(rows);
//        }
        tblDSDiem.setModel(tbl);
    }
    
    //<editor-fold defaultstate="collapsed" desc="CardLayout">
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardDashboard");
        reload();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardLop");
        reload();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardMon");
        reload();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardSV");
        reload();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardDiem");
        reload();
    }//GEN-LAST:event_jButton5ActionPerformed
//</editor-fold>
    
    private void mnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThoatActionPerformed
        String message = "Bạn có chắc chắn muốn thoát ?";
        String title = "Thoát";
        // display the JOptionPane showConfirmDialog
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_mnThoatActionPerformed

    private void DisEn(boolean e)
    {
    }    //</editor-fold>
    
        // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Diem">
    private void btnThemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemdiemActionPerformed
//        ThemDiemDialog d = new ThemDiemDialog(this, true);
//        d.setVisible(true);
//        reload();
    }//GEN-LAST:event_btnThemdiemActionPerformed

    private void btnSuadiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuadiemActionPerformed
//        int row = tblDSDiem.getSelectedRow();
//        String ma = tblDSDiem.getValueAt(row, 0).toString();
//        String tenmh = tblDSDiem.getValueAt(row, 3).toString();
//        String tenld = tblDSDiem.getValueAt(row, 4).toString();
//        SuaDiemDialog d = new SuaDiemDialog(this, true, ma,tenmh,tenld);
//        d.setVisible(true);
//        reload();
    }//GEN-LAST:event_btnSuadiemActionPerformed

    private void btnXoadiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoadiemActionPerformed
//        int row = tblDSDiem.getSelectedRow();
//        String ma = tblDSDiem.getValueAt(row, 0).toString();
//        int mamh = 0,mald = 0;
//        List<MonHoc> listmh = monDAO.getAll();
//        for (int i = 0; i < listmh.size(); i++) {
//            MonHoc mh = listmh.get(i);
//            String tenmh = tblDSDiem.getValueAt(row, 3).toString();
//            if(tenmh.equals(mh.getTenMH()))
//                mamh = mh.getMaMH();       
//        }
//        
//        List<LoaiDiem> listld = ldDAO.getAll();
//        for (int j = 0; j < listld.size(); j++) {
//            LoaiDiem ld = listld.get(j);
//            String tenld = tblDSDiem.getValueAt(row, 4).toString();
//            if(tenld.equals(ld.getTenLoai()))
//                mald = ld.getMaLoai();
//        }
//        
//        
//        int i = JOptionPane.showConfirmDialog(pnlContent,"Bạn có chắc chắn muốn xóa ?","Xóa",JOptionPane.YES_NO_OPTION);
//        if(i==JOptionPane.YES_OPTION)
//        {
//            if(diemDAO.XoaDiem(ma,mamh,mald))
//                JOptionPane.showMessageDialog(pnlContent, "Xóa thành công");
//            else
//                JOptionPane.showMessageDialog(pnlContent, "Xóa thất bại");
//            
//            loadDSDiem();
//        }
    }//GEN-LAST:event_btnXoadiemActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
//        ChitietDialog d = new ChitietDialog(this, true);
//        d.setVisible(true);
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void tblDSDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSDiemMouseClicked
        DisEn(true);
    }//GEN-LAST:event_tblDSDiemMouseClicked

    private void mnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDangXuatActionPerformed
        this.dispose();
        LoginForm login = new LoginForm(this);
        System.setProperty("Admin", "");
        login.setVisible(true);
    }//GEN-LAST:event_mnDangXuatActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        int row = tblStudent.getSelectedRow();
        txtStudentId.setText(tblStudent.getValueAt(row, 0).toString());
        txtStudentName.setText(tblStudent.getValueAt(row, 1).toString());
        txtBirthday.setText(tblStudent.getValueAt(row, 2).toString());
        String gender = tblStudent.getValueAt(row, 3).toString();
        if(gender.equals("Nam")){
            radioMale.setSelected(true);
        } else if(gender.equals("Nữ")){
            radioFemale.setSelected(true);
        }
        String className =  tblStudent.getValueAt(row, 5).toString();
        for(int i = 0;i<cbClass.getMaximumRowCount();i++){
            if(cbClass.getItemAt(i).equals(className)){
                cbClass.setSelectedIndex(i);
            }
        }
        txtAddress.setText(tblStudent.getValueAt(row, 4).toString());
        btnAddStudent.setEnabled(false);
        btnUpdateStudent.setEnabled(true);
        btnDeleteStudent.setEnabled(true);
    }//GEN-LAST:event_tblStudentMouseClicked

    private void tblClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClassMouseClicked
        int row = tblClass.getSelectedRow();
        txtClassId.setText(tblClass.getValueAt(row, 0).toString());
        txtClassName.setText(tblClass.getValueAt(row, 1).toString());
        btnAddClass.setEnabled(false);
        btnUpdateClass.setEnabled(true);
        btnDeleteClass.setEnabled(true);
    }//GEN-LAST:event_tblClassMouseClicked

    private void tblSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSubjectMouseClicked
        int row = tblSubject.getSelectedRow();
        txtSubjectId.setText(tblSubject.getValueAt(row, 0).toString());
        txtSubjectName.setText(tblSubject.getValueAt(row, 1).toString());
        btnAddSubject.setEnabled(false);
        btnUpdateSubject.setEnabled(true);
        btnDeleteSubject.setEnabled(true);
    }//GEN-LAST:event_tblSubjectMouseClicked

    private void btnAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSubjectActionPerformed
        Subject subject = new Subject();
        subject.setName(txtSubjectName.getText());
        try {
            subjectController.addSubject(subject);
            JOptionPane.showMessageDialog(null,"Thêm mới thành công");
        } catch (Exception e) {
            System.out.println("Add failed");
            JOptionPane.showMessageDialog(null,"Thêm mới không thành công");
        }
        loadSubjectList();
        loadSubjectList();
    }//GEN-LAST:event_btnAddSubjectActionPerformed

    private void btnUpdateSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSubjectActionPerformed
        Subject subject = new Subject();
        subject.setId(Integer.parseInt(txtSubjectId.getText()));
        subject.setName(txtSubjectName.getText());
        try {
            subjectController.updateSubject(subject);
            JOptionPane.showMessageDialog(null,"Sửa thành công");
        } catch (Exception e) {
            System.out.println("Update failed");
            JOptionPane.showMessageDialog(null,"Sửa không thành công");
        }
        loadSubjectList();
    }//GEN-LAST:event_btnUpdateSubjectActionPerformed

    private void btnDeleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSubjectActionPerformed
        if(subjectController.deleteSubject(Integer.parseInt(txtSubjectId.getText()))){
            JOptionPane.showMessageDialog(null,"Xóa thành công");
            ((DefaultTableModel)tblSubject.getModel()).removeRow(tblSubject.getSelectedRow());
            tblSubject.clearSelection();
            txtSubjectId.setText("");
            txtSubjectName.setText("");
            loadSubjectList();
        } else {
            System.out.println("Delete failed");
            JOptionPane.showMessageDialog(null,"Xóa không thành công");
        }
    }//GEN-LAST:event_btnDeleteSubjectActionPerformed

    private void btnClearSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSubjectActionPerformed
        txtSubjectId.setText("");
        txtSubjectName.setText("");
        btnAddSubject.setEnabled(true);
        btnUpdateSubject.setEnabled(false);
        btnDeleteSubject.setEnabled(false);
    }//GEN-LAST:event_btnClearSubjectActionPerformed

    private void btnAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClassActionPerformed
        Classes clazz = new Classes();
        clazz.setName(txtClassName.getText());
        try {
            classController.addClass(clazz);
            JOptionPane.showMessageDialog(null,"Thêm mới thành công");
        } catch (Exception e) {
            System.out.println("Add failed");
            JOptionPane.showMessageDialog(null,"Thêm mới không thành công");
        }
        loadClassList();
        loadClassList();
    }//GEN-LAST:event_btnAddClassActionPerformed

    private void btnUpdateClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateClassActionPerformed
        Classes clazz = new Classes();
        clazz.setId(Integer.parseInt(txtClassId.getText()));
        clazz.setName(txtClassName.getText());
        try {
            classController.updateClass(clazz);
            JOptionPane.showMessageDialog(null,"Sửa thành công");
        } catch (Exception e) {
            System.out.println("Update failed");
            JOptionPane.showMessageDialog(null,"Sửa không thành công");
        }
        loadClassList();
    }//GEN-LAST:event_btnUpdateClassActionPerformed

    private void btnDeleteClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClassActionPerformed
        if(classController.deleteClass(Integer.parseInt(txtClassId.getText()))){
            JOptionPane.showMessageDialog(null,"Xóa thành công");
            ((DefaultTableModel)tblClass.getModel()).removeRow(tblClass.getSelectedRow());
            tblClass.clearSelection();
            txtClassId.setText("");
            txtClassName.setText("");
            loadClassList();
        } else {
            System.out.println("Delete failed");
            JOptionPane.showMessageDialog(null,"Xóa không thành công");
        }
    }//GEN-LAST:event_btnDeleteClassActionPerformed

    private void btnClearClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearClassActionPerformed
        txtClassId.setText("");
        txtClassName.setText("");
        btnAddClass.setEnabled(true);
        btnUpdateClass.setEnabled(false);
        btnDeleteClass.setEnabled(false);
    }//GEN-LAST:event_btnClearClassActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        Student student = new Student();
        student.setName(txtStudentName.getText());
        if(radioMale.isSelected()){
            student.setGender(false);
        } else if(radioFemale.isSelected()) {
            student.setGender(true);
        }
        student.setBirthday(txtBirthday.getText());
        student.setAddress(txtAddress.getText());
        student.setClazz(classController.getClassById((int) classId.get(cbClass.getSelectedIndex())));
        try {
            studentController.addStudent(student);
            JOptionPane.showMessageDialog(null,"Thêm mới thành công");
        } catch (Exception e) {
            System.out.println("Add failed");
            JOptionPane.showMessageDialog(null,"Thêm mới không thành công");
        }
        loadStudentList();
        loadStudentList();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudentActionPerformed
        Student student = new Student();
        student.setId(Integer.parseInt(txtStudentId.getText()));
        student.setName(txtStudentName.getText());
        if(radioMale.isSelected()){
            student.setGender(false);
        } else if(radioFemale.isSelected()) {
            student.setGender(true);
        }
        student.setBirthday(txtBirthday.getText());
        student.setAddress(txtAddress.getText());
        try {
            studentController.updateStudent(student);
            JOptionPane.showMessageDialog(null,"Sửa thành công");
        } catch (Exception e) {
            System.out.println("Update failed");
            JOptionPane.showMessageDialog(null,"Sửa không thành công");
        }
        loadStudentList();
    }//GEN-LAST:event_btnUpdateStudentActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        if(studentController.deleteStudent(Integer.parseInt(txtStudentId.getText()))){
            JOptionPane.showMessageDialog(null,"Xóa thành công");
            ((DefaultTableModel)tblStudent.getModel()).removeRow(tblStudent.getSelectedRow());
            tblStudent.clearSelection();
            txtStudentId.setText("");
            txtStudentName.setText("");
            txtAddress.setText("");
            txtBirthday.setText("");
            genderBtnGroup.clearSelection();
            loadStudentList();
        } else {
            System.out.println("Delete failed");
            JOptionPane.showMessageDialog(null,"Xóa không thành công");
        }
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnClearStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearStudentActionPerformed
        txtStudentId.setText("");
        txtStudentName.setText("");
        txtAddress.setText("");
        txtBirthday.setText("");
        genderBtnGroup.clearSelection();
        btnAddStudent.setEnabled(true);
        btnUpdateStudent.setEnabled(false);
        btnDeleteStudent.setEnabled(false);
    }//GEN-LAST:event_btnClearStudentActionPerformed

    private void test1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test1ActionPerformed
        System.out.println(cbClass.getSelectedIndex());
    }//GEN-LAST:event_test1ActionPerformed
    //</editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClass;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAddSubject;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnClearClass;
    private javax.swing.JButton btnClearStudent;
    private javax.swing.JButton btnClearSubject;
    private javax.swing.JButton btnDeleteClass;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnDeleteSubject;
    private javax.swing.JButton btnSuadiem;
    private javax.swing.JButton btnThemdiem;
    private javax.swing.JButton btnUpdateClass;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JButton btnUpdateSubject;
    private javax.swing.JButton btnXoadiem;
    private javax.swing.JComboBox<String> cbClass;
    private javax.swing.ButtonGroup genderBtnGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JMenuItem mnDangXuat;
    private javax.swing.JMenuItem mnThoat;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlDSSV1;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDiem;
    private javax.swing.JPanel pnlLop;
    private javax.swing.JPanel pnlMon;
    private javax.swing.JPanel pnlSV;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTable tblClass;
    private javax.swing.JTable tblDSDiem;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTable tblSubject;
    private javax.swing.JButton test1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtClassId;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtSubjectId;
    private javax.swing.JTextField txtSubjectName;
    // End of variables declaration//GEN-END:variables
}
