/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aptech.qldsv.form;

import com.aptech.qldsv.controller.ScoreController;
import com.aptech.qldsv.dto.StudentScoreDTO;
import com.aptech.qldsv.entity.Classes;
import com.aptech.qldsv.entity.Student;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author skulb
 */
public class StudentScoreDialog extends javax.swing.JDialog {
    
    ScoreController scoreController =  new ScoreController();

    /**
     * Creates new form StudentScoreDialog
     */
    public StudentScoreDialog(java.awt.Frame parent, boolean modal,int id) {
        super(parent, modal);
        initComponents();
        loadData(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScollPane1 = new javax.swing.JScrollPane();
        tblStudentScore = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bảng điểm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        tblStudentScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScollPane1.setViewportView(tblStudentScore);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(int id){
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[4];
        Object cols[] = new Object[4];
        cols[0] = "Môn học";
        cols[1] = "Chuyên cần";
        cols[2] = "Giữa kì";
        cols[3] = "Cuối kì";
        
        tbl.setColumnIdentifiers(cols);
        
        List<StudentScoreDTO> list = scoreController.getScoreByStudent(id);
        for (StudentScoreDTO s : list) {
            rows[0] = s.getSubjectName();
            if(s.getScore1()!=null){
                rows[1] = s.getScore1();
            } else {
                rows[1] = "TBD";
            }
            if(s.getScore2()!=null){
                rows[2] = s.getScore2();
            } else {
                rows[2] = "TBD";
            }
            if(s.getScore3()!=null){
                rows[3] = s.getScore3();
            } else {
                rows[3] = "TBD";
            }
            tbl.addRow(rows);
        }

        tblStudentScore.setModel(tbl);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScollPane1;
    private javax.swing.JTable tblStudentScore;
    // End of variables declaration//GEN-END:variables
}
